import Head from "next/head";
import Image from "next/image";
import Link from "next/link";

export default function Home() {
  return (
    <main className="w-full h-screen flex items-center justify-center">
      <Head>
        <title>Stienis</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Image
        src="/home.jpg"
        alt="Anime girl"
        width={400}
        height={800}
        className="w-full h-full object-cover"
      />

      <div className="absolute top-0 left-0 w-full h-full flex items-center justify-center">
        <Link href="/game" className="text-5xl text-blue-700">Aiziet</Link>
      </div>
    </main>
  );
}
